### ISSUE TITLE
Still leaks internal IP in some cases

### ISSUE THREAD

**Issue by odegroot** [Ekus/CourtesyRedirectOverride#1]
This module passes a URL _without_ hostname to `Response.Redirect(...)`, but `HttpResponse.Redirect()` _still_ has logic that sometimes adds the domain name.

```cs
internal void Redirect(String url, bool endResponse, bool permanent) {
    (...)
    url = ConvertToFullyQualifiedRedirectUrlIfRequired(url);
    (...)
}
```
Source: https://github.com/microsoft/referencesource/blob/master/System.Web/HttpResponse.cs#L2372

Steps to reproduce, using powershell, openssl and HTTP/1.0:
```
Write-Output "GET /MyApp HTTP/1.0`n`n" | openssl s_client -host localhost -port 443
(...)
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: https://[::1]/MyApp/
Server: Microsoft-IIS/10.0
X-Test: CourtesyRedirectOverride by .net module
(...)
```

**Comment by Ekus** [comment]
Thank you for the great bug report. Unfortunately, this project is no longer actively updated, but please feel free to submit a pull request if you're able to handle the special case.
